'use strict';
async function createDatabaseUsingAutogeneratedCode(instanceID, databaseID, projectID) {
    const { DatabaseAdminClient } = require('@google-cloud/spanner/build/src/v1');
    const databaseAdminClient = new DatabaseAdminClient({
        projectID: projectID,
        instanceID: instanceID,
    });


   const createSingersTableStatement = `
    CREATE TABLE Singers (
        SingerId   INT64 NOT NULL,
        FirstName  STRING(1024),
        LastName   STRING(1024),
        SingerInfo BYTES(MAX)
    ) PRIMARY KEY (SingerId)`;
    const createAlbumsTableStatement = `
    CREATE TABLE Albums (
        SingerId     INT64 NOT NULL,
        AlbumId      INT64 NOT NULL,
        AlbumTitle   STRING(MAX)
    ) PRIMARY KEY (SingerId, AlbumId),
        INTERLEAVE IN PARENT Singers ON DELETE CASCADE`;


    try {
        const [operation] = await databaseAdminClient.createDatabase({
            createStatement: 'CREATE DATABASE `' + databaseID + '`',
            extraStatements: [createSingersTableStatement, createAlbumsTableStatement],
            parent: databaseAdminClient.instancePath(projectID, instanceID),
        })


        console.log(`Waiting for creation of ${databaseID} to complete...`);
        await operation.promise();

        console.log(
            `Created database ${databaseID} on instance ${instanceID}.`
        );
    } catch (err) {
        console.error('ERROR:', err);
    } finally {
        databaseAdminClient.close();
    }
}

// createDatabaseUsingAutogeneratedCode("alka-test-1", "testdatabaseforautogenclient","span-cloud-testing")

require('yargs')
  .demand(1)
  .command(
    'createDatabaseUsingAutogeneratedCode <instanceName> <databaseName> <projectId>',
    'Creates an example database with two tables in a Cloud Spanner instance.',
    {},
    opts => createDatabaseUsingAutogeneratedCode(opts.instanceName, opts.databaseName, opts.projectId)
  )
  .example('node $0 createDatabaseUsingAutogeneratedCode "my-instance" "my-database" "my-project-id"')
  .wrap(120)
  .recommendCommands()
  .epilogue('For more information, see https://cloud.google.com/spanner/docs')
  .strict()
  .help().argv;
