'use strict';

async function createInstanceUsingAutogeneratedCode(instanceID, projectID){
    const { InstanceAdminClient } = require('@google-cloud/spanner/build/src/v1');
   
    const instanceAdminClient = new InstanceAdminClient({
        projectId: projectID
    });
   
    // Creates a new instance
    try {
        const [operation] = await instanceAdminClient.createInstance({
            instanceId: instanceID,
            instance: {
                config: instanceAdminClient.instanceConfigPath(projectID, 'regional-us-central1'),
                displayName: 'Display name for the instance.',
                nodeCount: 1
            },
            parent: instanceAdminClient.projectPath(projectID),
        })
 
 
        console.log(`Waiting for operation on ${instanceID} to complete...`);
        await operation.promise();
        console.log(`Created instance ${instanceID}.`);
    } catch (err) {
        console.error('ERROR:', err);
    } finally {
        instanceAdminClient.close();
    }
}


require('yargs')
  .demand(1)
  .command(
    'createInstanceUsingAutogeneratedCode <instanceName> <projectId>',
    'Creates an example instance in a Cloud Spanner instance using autogenerated code.',
    {},
    opts => createInstanceUsingAutogeneratedCode(opts.instanceName, opts.projectId)
  )
  .example('node $0 createInstanceUsingAutogeneratedCode "my-instance" "my-project-id"')
  .wrap(120)
  .recommendCommands()
  .epilogue('For more information, see https://cloud.google.com/spanner/docs')
  .strict()
  .help().argv;

// createInstanceUsingAutogeneratedCode("alka-test-1", "span-cloud-testing");